// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{0}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type TransactionReply struct {
	Transactions         []*TransactionInformation `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TransactionReply) Reset()         { *m = TransactionReply{} }
func (m *TransactionReply) String() string { return proto.CompactTextString(m) }
func (*TransactionReply) ProtoMessage()    {}
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{1}
}

func (m *TransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReply.Unmarshal(m, b)
}
func (m *TransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReply.Marshal(b, m, deterministic)
}
func (m *TransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReply.Merge(m, src)
}
func (m *TransactionReply) XXX_Size() int {
	return xxx_messageInfo_TransactionReply.Size(m)
}
func (m *TransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReply proto.InternalMessageInfo

func (m *TransactionReply) GetTransactions() []*TransactionInformation {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type TransactionInformation struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string               `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount               int64                `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string               `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Merchant             string               `protobuf:"bytes,7,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Notes                string               `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	Settled              *timestamp.Timestamp `protobuf:"bytes,9,opt,name=settled,proto3" json:"settled,omitempty"`
	UserId               string               `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsLoad               bool                 `protobuf:"varint,11,opt,name=is_load,json=isLoad,proto3" json:"is_load,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated,proto3" json:"updated,omitempty"`
	LocalAmount          float32              `protobuf:"fixed32,13,opt,name=local_amount,json=localAmount,proto3" json:"local_amount,omitempty"`
	LocalCurrency        string               `protobuf:"bytes,14,opt,name=local_currency,json=localCurrency,proto3" json:"local_currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionInformation) Reset()         { *m = TransactionInformation{} }
func (m *TransactionInformation) String() string { return proto.CompactTextString(m) }
func (*TransactionInformation) ProtoMessage()    {}
func (*TransactionInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{2}
}

func (m *TransactionInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInformation.Unmarshal(m, b)
}
func (m *TransactionInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInformation.Marshal(b, m, deterministic)
}
func (m *TransactionInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInformation.Merge(m, src)
}
func (m *TransactionInformation) XXX_Size() int {
	return xxx_messageInfo_TransactionInformation.Size(m)
}
func (m *TransactionInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInformation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInformation proto.InternalMessageInfo

func (m *TransactionInformation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransactionInformation) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *TransactionInformation) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *TransactionInformation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TransactionInformation) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionInformation) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *TransactionInformation) GetMerchant() string {
	if m != nil {
		return m.Merchant
	}
	return ""
}

func (m *TransactionInformation) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *TransactionInformation) GetSettled() *timestamp.Timestamp {
	if m != nil {
		return m.Settled
	}
	return nil
}

func (m *TransactionInformation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TransactionInformation) GetIsLoad() bool {
	if m != nil {
		return m.IsLoad
	}
	return false
}

func (m *TransactionInformation) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *TransactionInformation) GetLocalAmount() float32 {
	if m != nil {
		return m.LocalAmount
	}
	return 0
}

func (m *TransactionInformation) GetLocalCurrency() string {
	if m != nil {
		return m.LocalCurrency
	}
	return ""
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "transaction.TransactionRequest")
	proto.RegisterType((*TransactionReply)(nil), "transaction.TransactionReply")
	proto.RegisterType((*TransactionInformation)(nil), "transaction.TransactionInformation")
}

func init() { proto.RegisterFile("proto/transaction.proto", fileDescriptor_80e80868f3cd63d0) }

var fileDescriptor_80e80868f3cd63d0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0xae, 0x9a, 0x40,
	0x14, 0x2e, 0xd0, 0x8b, 0x7a, 0xf0, 0xda, 0x66, 0xd2, 0xdc, 0x3b, 0x21, 0x31, 0x52, 0x9a, 0x26,
	0xac, 0x30, 0xd1, 0xbe, 0x40, 0xd3, 0x85, 0x31, 0xe9, 0x8a, 0xba, 0xeb, 0xc2, 0x8c, 0x33, 0xa3,
	0x25, 0x01, 0x86, 0xce, 0x0c, 0x0b, 0x1f, 0xba, 0xef, 0xd0, 0x30, 0x0c, 0x16, 0x4d, 0x8d, 0xcb,
	0xf3, 0xfd, 0xcc, 0xf9, 0xf8, 0x38, 0xf0, 0x5a, 0x4b, 0xa1, 0xc5, 0x52, 0x4b, 0x52, 0x29, 0x42,
	0x75, 0x2e, 0xaa, 0xd4, 0x20, 0x28, 0x18, 0x40, 0xe1, 0xe2, 0x24, 0xc4, 0xa9, 0xe0, 0x4b, 0x43,
	0x1d, 0x9a, 0xe3, 0x52, 0xe7, 0x25, 0x57, 0x9a, 0x94, 0x75, 0xa7, 0x8e, 0xd7, 0x80, 0x76, 0xff,
	0xf4, 0x19, 0xff, 0xdd, 0x70, 0xa5, 0xd1, 0x1c, 0x80, 0x50, 0x2a, 0x9a, 0x4a, 0xef, 0x73, 0x86,
	0x9d, 0xc8, 0x49, 0x26, 0xd9, 0xc4, 0x22, 0x5b, 0x16, 0xff, 0x84, 0xf7, 0x57, 0xa6, 0xba, 0x38,
	0xa3, 0x0d, 0x4c, 0x07, 0x8b, 0x15, 0x76, 0x22, 0x2f, 0x09, 0x56, 0x9f, 0xd2, 0x61, 0xc0, 0x81,
	0x69, 0x5b, 0x1d, 0x85, 0x2c, 0x89, 0xf1, 0x5f, 0x19, 0xe3, 0x3f, 0x1e, 0xbc, 0xfc, 0x5f, 0x88,
	0x66, 0xe0, 0xda, 0x38, 0x5e, 0xe6, 0xe6, 0xec, 0x26, 0xa6, 0x7b, 0x13, 0x13, 0x7d, 0x81, 0x11,
	0x95, 0x9c, 0x68, 0xce, 0xb0, 0x17, 0x39, 0x49, 0xb0, 0x0a, 0xd3, 0xae, 0x8e, 0xb4, 0xaf, 0x23,
	0xdd, 0xf5, 0x75, 0x64, 0xbd, 0x14, 0x45, 0x10, 0x30, 0xae, 0xa8, 0xcc, 0xeb, 0x76, 0x27, 0x7e,
	0x6b, 0x5e, 0x1d, 0x42, 0xe8, 0x05, 0x7c, 0x52, 0xb6, 0x3b, 0xf0, 0x93, 0x89, 0x62, 0x27, 0x14,
	0xc2, 0x98, 0x36, 0x52, 0xf2, 0x8a, 0x9e, 0xb1, 0x6f, 0x6c, 0x97, 0xb9, 0xe5, 0x4a, 0x2e, 0xe9,
	0x2f, 0x52, 0x69, 0x3c, 0xea, 0xb8, 0x7e, 0x46, 0x1f, 0xe0, 0xa9, 0x12, 0x9a, 0x2b, 0x3c, 0x36,
	0x44, 0x37, 0xb4, 0xe9, 0x15, 0xd7, 0xba, 0xe0, 0x0c, 0x4f, 0x1e, 0xa7, 0xb7, 0x52, 0xf4, 0x0a,
	0xa3, 0x46, 0x71, 0xd9, 0xf6, 0x01, 0xe6, 0x35, 0xbf, 0x1d, 0xb7, 0x86, 0xc8, 0xd5, 0xbe, 0x10,
	0x84, 0xe1, 0x20, 0x72, 0x92, 0x71, 0xe6, 0xe7, 0xea, 0xbb, 0x20, 0xa6, 0xa5, 0xa6, 0x66, 0xa6,
	0xa5, 0xe9, 0xe3, 0x3d, 0x56, 0x8a, 0x3e, 0xc2, 0xb4, 0x10, 0x94, 0x14, 0x7b, 0xdb, 0xc4, 0x73,
	0xe4, 0x24, 0x6e, 0x16, 0x18, 0xec, 0x6b, 0x57, 0xc7, 0x67, 0x98, 0x75, 0x92, 0x4b, 0x29, 0x33,
	0x93, 0xe8, 0xd9, 0xa0, 0xdf, 0x2c, 0xb8, 0x3a, 0x40, 0x30, 0xf8, 0xdd, 0xe8, 0x07, 0xbc, 0xdb,
	0x70, 0x3d, 0x40, 0x14, 0x5a, 0xdc, 0x3b, 0x22, 0x7b, 0xae, 0xe1, 0xfc, 0xbe, 0xa0, 0x2e, 0xce,
	0xf1, 0x9b, 0x83, 0x6f, 0x3e, 0x65, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x2a, 0x70, 0x6f,
	0x35, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	GetTransactions(context.Context, *TransactionRequest) (*TransactionReply, error)
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetTransactions(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _Transaction_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction.proto",
}
