// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{0}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type TransactionReply struct {
	Transactions         []*TransactionInformation `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TransactionReply) Reset()         { *m = TransactionReply{} }
func (m *TransactionReply) String() string { return proto.CompactTextString(m) }
func (*TransactionReply) ProtoMessage()    {}
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{1}
}

func (m *TransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReply.Unmarshal(m, b)
}
func (m *TransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReply.Marshal(b, m, deterministic)
}
func (m *TransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReply.Merge(m, src)
}
func (m *TransactionReply) XXX_Size() int {
	return xxx_messageInfo_TransactionReply.Size(m)
}
func (m *TransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReply proto.InternalMessageInfo

func (m *TransactionReply) GetTransactions() []*TransactionInformation {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type TransactionInformation struct {
	Id                         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId                  string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Created                    int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Description                string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount                     int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency                   string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Merchant                   string   `protobuf:"bytes,7,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Notes                      string   `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	Settled                    int64    `protobuf:"varint,9,opt,name=settled,proto3" json:"settled,omitempty"`
	UserId                     string   `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsLoad                     bool     `protobuf:"varint,11,opt,name=is_load,json=isLoad,proto3" json:"is_load,omitempty"`
	Updated                    int64    `protobuf:"varint,12,opt,name=updated,proto3" json:"updated,omitempty"`
	LocalAmount                int64    `protobuf:"varint,13,opt,name=local_amount,json=localAmount,proto3" json:"local_amount,omitempty"`
	LocalCurrency              string   `protobuf:"bytes,14,opt,name=local_currency,json=localCurrency,proto3" json:"local_currency,omitempty"`
	IncludeInSpending          bool     `protobuf:"varint,15,opt,name=include_in_spending,json=includeInSpending,proto3" json:"include_in_spending,omitempty"`
	CanBeExcludedFromBreakdown bool     `protobuf:"varint,16,opt,name=can_be_excluded_from_breakdown,json=canBeExcludedFromBreakdown,proto3" json:"can_be_excluded_from_breakdown,omitempty"`
	CanBeMadeSubscription      bool     `protobuf:"varint,17,opt,name=can_be_made_subscription,json=canBeMadeSubscription,proto3" json:"can_be_made_subscription,omitempty"`
	CanSplitTheBill            bool     `protobuf:"varint,18,opt,name=can_split_the_bill,json=canSplitTheBill,proto3" json:"can_split_the_bill,omitempty"`
	CanAddToTab                bool     `protobuf:"varint,19,opt,name=can_add_to_tab,json=canAddToTab,proto3" json:"can_add_to_tab,omitempty"`
	AmountIsPending            bool     `protobuf:"varint,20,opt,name=amount_is_pending,json=amountIsPending,proto3" json:"amount_is_pending,omitempty"`
	DeclineReason              string   `protobuf:"bytes,21,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Category                   string   `protobuf:"bytes,22,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *TransactionInformation) Reset()         { *m = TransactionInformation{} }
func (m *TransactionInformation) String() string { return proto.CompactTextString(m) }
func (*TransactionInformation) ProtoMessage()    {}
func (*TransactionInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{2}
}

func (m *TransactionInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInformation.Unmarshal(m, b)
}
func (m *TransactionInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInformation.Marshal(b, m, deterministic)
}
func (m *TransactionInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInformation.Merge(m, src)
}
func (m *TransactionInformation) XXX_Size() int {
	return xxx_messageInfo_TransactionInformation.Size(m)
}
func (m *TransactionInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInformation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInformation proto.InternalMessageInfo

func (m *TransactionInformation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionInformation) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *TransactionInformation) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TransactionInformation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TransactionInformation) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionInformation) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *TransactionInformation) GetMerchant() string {
	if m != nil {
		return m.Merchant
	}
	return ""
}

func (m *TransactionInformation) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *TransactionInformation) GetSettled() int64 {
	if m != nil {
		return m.Settled
	}
	return 0
}

func (m *TransactionInformation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TransactionInformation) GetIsLoad() bool {
	if m != nil {
		return m.IsLoad
	}
	return false
}

func (m *TransactionInformation) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *TransactionInformation) GetLocalAmount() int64 {
	if m != nil {
		return m.LocalAmount
	}
	return 0
}

func (m *TransactionInformation) GetLocalCurrency() string {
	if m != nil {
		return m.LocalCurrency
	}
	return ""
}

func (m *TransactionInformation) GetIncludeInSpending() bool {
	if m != nil {
		return m.IncludeInSpending
	}
	return false
}

func (m *TransactionInformation) GetCanBeExcludedFromBreakdown() bool {
	if m != nil {
		return m.CanBeExcludedFromBreakdown
	}
	return false
}

func (m *TransactionInformation) GetCanBeMadeSubscription() bool {
	if m != nil {
		return m.CanBeMadeSubscription
	}
	return false
}

func (m *TransactionInformation) GetCanSplitTheBill() bool {
	if m != nil {
		return m.CanSplitTheBill
	}
	return false
}

func (m *TransactionInformation) GetCanAddToTab() bool {
	if m != nil {
		return m.CanAddToTab
	}
	return false
}

func (m *TransactionInformation) GetAmountIsPending() bool {
	if m != nil {
		return m.AmountIsPending
	}
	return false
}

func (m *TransactionInformation) GetDeclineReason() string {
	if m != nil {
		return m.DeclineReason
	}
	return ""
}

func (m *TransactionInformation) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "transaction.TransactionRequest")
	proto.RegisterType((*TransactionReply)(nil), "transaction.TransactionReply")
	proto.RegisterType((*TransactionInformation)(nil), "transaction.TransactionInformation")
}

func init() { proto.RegisterFile("proto/transaction.proto", fileDescriptor_80e80868f3cd63d0) }

var fileDescriptor_80e80868f3cd63d0 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x4f, 0xdb, 0x3c,
	0x14, 0x7e, 0x0b, 0x2f, 0x01, 0x4e, 0xa0, 0x80, 0xf9, 0xb2, 0x90, 0xd8, 0xba, 0x22, 0xa4, 0x6a,
	0x93, 0x98, 0x04, 0x17, 0xbb, 0xa6, 0xd3, 0x86, 0x2a, 0x6d, 0xd2, 0xd4, 0xf6, 0x6e, 0x17, 0x96,
	0x63, 0x1f, 0xc0, 0x9a, 0x63, 0x67, 0xb6, 0xa3, 0xad, 0xbf, 0x60, 0x7f, 0x7b, 0x8a, 0xe3, 0x42,
	0x40, 0xe3, 0xf2, 0xf9, 0x3a, 0x39, 0x8f, 0x6b, 0x17, 0x8e, 0x2b, 0x67, 0x83, 0x7d, 0x1f, 0x1c,
	0x37, 0x9e, 0x8b, 0xa0, 0xac, 0xb9, 0x88, 0x0c, 0xc9, 0x3b, 0xd4, 0xf0, 0x0a, 0xc8, 0xfc, 0x11,
	0x4e, 0xf1, 0x67, 0x8d, 0x3e, 0x90, 0x53, 0x00, 0x2e, 0x84, 0xad, 0x4d, 0x60, 0x4a, 0xd2, 0xde,
	0xa0, 0x37, 0xda, 0x9c, 0x6e, 0x26, 0x66, 0x22, 0x87, 0xdf, 0x61, 0xf7, 0x49, 0xa8, 0xd2, 0x0b,
	0x72, 0x03, 0x5b, 0x9d, 0xb9, 0x9e, 0xf6, 0x06, 0xab, 0xa3, 0xfc, 0xf2, 0xec, 0xa2, 0xfb, 0xfd,
	0x4e, 0x68, 0x62, 0x6e, 0xad, 0x2b, 0x79, 0xcc, 0x3f, 0x09, 0x0e, 0xff, 0x64, 0x70, 0xf4, 0x6f,
	0x23, 0xe9, 0xc3, 0xca, 0xc3, 0x3a, 0x2b, 0x4a, 0x3e, 0x5b, 0x73, 0xe5, 0xd9, 0x9a, 0x84, 0xc2,
	0xba, 0x70, 0xc8, 0x03, 0x4a, 0xba, 0x3a, 0xe8, 0x8d, 0x56, 0xa7, 0x4b, 0x48, 0x06, 0x90, 0x4b,
	0xf4, 0xc2, 0xa9, 0xaa, 0x99, 0x4b, 0xff, 0x8f, 0xc9, 0x2e, 0x45, 0x8e, 0x20, 0xe3, 0x65, 0x33,
	0x87, 0xae, 0xc5, 0x68, 0x42, 0xe4, 0x04, 0x36, 0x44, 0xed, 0x1c, 0x1a, 0xb1, 0xa0, 0x59, 0x8c,
	0x3d, 0xe0, 0x46, 0x2b, 0xd1, 0x89, 0x7b, 0x6e, 0x02, 0x5d, 0x6f, 0xb5, 0x25, 0x26, 0x07, 0xb0,
	0x66, 0x6c, 0x40, 0x4f, 0x37, 0xa2, 0xd0, 0x82, 0x66, 0x43, 0x8f, 0x21, 0x68, 0x94, 0x74, 0xb3,
	0xdd, 0x30, 0x41, 0x72, 0x0c, 0xeb, 0xb5, 0x47, 0xd7, 0xf4, 0x82, 0x98, 0xc8, 0x1a, 0x38, 0x89,
	0x82, 0xf2, 0x4c, 0x5b, 0x2e, 0x69, 0x3e, 0xe8, 0x8d, 0x36, 0xa6, 0x99, 0xf2, 0x5f, 0x2c, 0x8f,
	0x6d, 0xeb, 0x4a, 0xc6, 0xb6, 0x5b, 0xed, 0xac, 0x04, 0xc9, 0x1b, 0xd8, 0xd2, 0x56, 0x70, 0xcd,
	0x52, 0xa3, 0xed, 0x28, 0xe7, 0x91, 0xbb, 0x6e, 0x6b, 0x9d, 0x43, 0xbf, 0xb5, 0x3c, 0x94, 0xeb,
	0xc7, 0xaf, 0x6e, 0x47, 0xf6, 0xe3, 0xb2, 0xe1, 0x05, 0xec, 0x2b, 0x23, 0x74, 0x2d, 0x91, 0x29,
	0xc3, 0x7c, 0x85, 0x46, 0x2a, 0x73, 0x47, 0x77, 0xe2, 0x22, 0x7b, 0x49, 0x9a, 0x98, 0x59, 0x12,
	0xc8, 0x18, 0x5e, 0x09, 0x6e, 0x58, 0x81, 0x0c, 0x7f, 0x47, 0x4d, 0xb2, 0x5b, 0x67, 0x4b, 0x56,
	0x38, 0xe4, 0x3f, 0xa4, 0xfd, 0x65, 0xe8, 0x6e, 0x8c, 0x9e, 0x08, 0x6e, 0xc6, 0xf8, 0x29, 0x79,
	0x3e, 0x3b, 0x5b, 0x8e, 0x97, 0x0e, 0xf2, 0x01, 0x68, 0x9a, 0x51, 0x72, 0x89, 0xcc, 0xd7, 0xc5,
	0xe3, 0x0f, 0xb7, 0x17, 0xd3, 0x87, 0x31, 0xfd, 0x95, 0x4b, 0x9c, 0x75, 0x44, 0xf2, 0x0e, 0x48,
	0x13, 0xf4, 0x95, 0x56, 0x81, 0x85, 0x7b, 0x64, 0x85, 0xd2, 0x9a, 0x92, 0x18, 0xd9, 0x11, 0xdc,
	0xcc, 0x1a, 0x61, 0x7e, 0x8f, 0x63, 0xa5, 0x35, 0x39, 0x83, 0x7e, 0x63, 0xe6, 0x52, 0xb2, 0x60,
	0x59, 0xe0, 0x05, 0xdd, 0x8f, 0xc6, 0x5c, 0x70, 0x73, 0x2d, 0xe5, 0xdc, 0xce, 0x79, 0x41, 0xde,
	0xc2, 0x5e, 0x7b, 0x84, 0x4c, 0x79, 0xb6, 0x2c, 0x7f, 0xd0, 0x0e, 0x6c, 0x85, 0x89, 0xff, 0x96,
	0xaa, 0x9f, 0x43, 0x5f, 0xa2, 0xd0, 0xca, 0x20, 0x73, 0xc8, 0xbd, 0x35, 0xf4, 0xb0, 0x3d, 0xd1,
	0xc4, 0x4e, 0x23, 0x19, 0xef, 0x13, 0x0f, 0x78, 0x67, 0xdd, 0x82, 0x1e, 0xa5, 0xfb, 0x94, 0xf0,
	0x65, 0x01, 0x79, 0xe7, 0x21, 0x90, 0x19, 0xec, 0xdc, 0x60, 0xe8, 0x30, 0x9e, 0xbc, 0x7e, 0xe9,
	0x79, 0xa5, 0x87, 0x7c, 0x72, 0xfa, 0xb2, 0xa1, 0xd2, 0x8b, 0xe1, 0x7f, 0x45, 0x16, 0xff, 0x13,
	0xae, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x34, 0xcb, 0xa7, 0x1b, 0x2e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, "/transaction.Transaction/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	GetTransactions(context.Context, *TransactionRequest) (*TransactionReply, error)
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transaction/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetTransactions(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _Transaction_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction.proto",
}
